import json

# ─── 15 Business-aligned template categories ────────────────────────────────
# Based on competitive analysis: Pollo AI, GoEnhance, InVideo

TEMPLATE_CATEGORIES = [
    {
        "name": "pet_animal",
        "display_name": "宠物 / 动物",
        "description": "动物拟人化、宠物运动、搞笑动物 — Pollo Animal Olympics / pet diving",
        "patterns": json.dumps([
            r"\b(cat|cats|kitten|kitty|dog|dogs|puppy|puppies|pet|pets)\b",
            r"\b(animal|animals|hamster|rabbit|bunny|parrot|fish|bird|panda|bear|fox)\b",
            r"\b(meow|bark|paw|fur|breed|feline|canine)\b",
            r"\b(animal\s+olympics|pet\s+diving|working\s+pet|pet.to.human)\b",
            r"\b(talking\s+pet|dancing\s+(cat|dog|animal)|pet\s+reaction|cute\s+(cat|dog|pet))\b",
            r"\b(wildlife|zoo|farm\s+animal|forest\s+animal)\b",
        ]),
        "template_suggestions": json.dumps([
            "Animal Olympics video template",
            "Pet diving / swimming action",
            "Talking / reacting pet template",
            "Pet-to-human transformation",
            "Dancing cat / dog viral template",
            "Working pet comedy template",
        ]),
        "color": "#f59e0b",
    },
    {
        "name": "romance_social",
        "display_name": "情感互动 / 人物关系",
        "description": "kiss、hug、fake date、celebrity selfie — 情侣/粉圈/社媒整活",
        "patterns": json.dumps([
            r"\b(kiss|kissing|french\s+kiss|hug|hugging|embrace|cuddle)\b",
            r"\b(fake\s+date|celebrity\s+selfie|celebrity\s+hug|celebrity\s+kiss)\b",
            r"\b(couple|couples|romantic|romance|love|lover|girlfriend|boyfriend)\b",
            r"\b(wedding|proposal|anniversary|valentine|date\s+night)\b",
            r"\b(heart|soulmate|together|holding\s+hands|slow\s+dance)\b",
            r"\b(friendship|friends\s+video|bestie|bff|sibling)\b",
        ]),
        "template_suggestions": json.dumps([
            "AI kiss / hug video generator",
            "Fake celebrity date template",
            "Couple photo animation",
            "Valentine's video maker",
            "Celebrity selfie AI template",
            "Friendship highlight reel",
        ]),
        "color": "#f43f5e",
    },
    {
        "name": "sports_action",
        "display_name": "运动 / 竞技",
        "description": "体育、健身、动作挑战 — InVideo home workout / Pollo Animal Olympics",
        "patterns": json.dumps([
            r"\b(sport|sports|athletic|athlete|workout|fitness|gym|exercise)\b",
            r"\b(basketball|football|soccer|tennis|baseball|golf|swimming|running)\b",
            r"\b(challenge|competition|tournament|match|game|race|marathon)\b",
            r"\b(jump|dunk|kick|punch|score|goal|slam|tackle)\b",
            r"\b(home\s+workout|training\s+video|sports\s+highlight|game\s+recap)\b",
            r"\b(olympic|champion|league|playoff|superbowl|super\s+bowl|nba|nfl|fifa)\b",
        ]),
        "template_suggestions": json.dumps([
            "Sports highlight reel template",
            "Home workout video maker",
            "Athletic challenge template",
            "Game day recap video",
            "Training montage template",
            "Sports event promo",
        ]),
        "color": "#0ea5e9",
    },
    {
        "name": "cinematic_story",
        "display_name": "影视 / 叙事 / 电影感",
        "description": "短剧感、片头、叙事 — InVideo Cinematic Noir / Storytelling",
        "patterns": json.dumps([
            r"\b(cinematic|cinema|movie|film|short\s+film|short\s+movie)\b",
            r"\b(noir|thriller|drama|mystery|storytelling|narrative|plot)\b",
            r"\b(scene|screenplay|director|director.?s\s+cut|movie\s+trailer|trailer)\b",
            r"\b(horror|sci.fi|fantasy|action\s+movie|rom.?com|documentary)\b",
            r"\b(opening\s+(credits?|scene|title)|movie\s+intro|film\s+intro)\b",
            r"\b(character|protagonist|villain|hero|plot\s+twist)\b",
        ]),
        "template_suggestions": json.dumps([
            "Cinematic noir short film template",
            "Movie trailer maker",
            "Storytelling video template",
            "Mystery / thriller intro",
            "Short drama scene generator",
            "Film opening credits template",
        ]),
        "color": "#6366f1",
    },
    {
        "name": "music_dance",
        "display_name": "音乐 / 舞蹈 / 演出",
        "description": "music video、dance、AI lip sync — GoEnhance / InVideo Performances",
        "patterns": json.dumps([
            r"\b(music\s+video|music\s+maker|music\s+generator|ai\s+music)\b",
            r"\b(dance|dancing|dancer|choreography|tiktok\s+dance)\b",
            r"\b(lip\s+sync|lipsync|singing|sing|karaoke|a\s+cappella)\b",
            r"\b(performance|concert|stage|live\s+show|band|orchestra)\b",
            r"\b(beat|rhythm|dj|remix|track|song|melody|bpm)\b",
            r"\b(music\s+visualizer|lyric\s+video|album\s+(cover|art)|music\s+reel)\b",
        ]),
        "template_suggestions": json.dumps([
            "AI music video generator",
            "TikTok dance challenge template",
            "AI lip sync video maker",
            "Music visualizer template",
            "Concert / performance highlight",
            "Lyric video generator",
        ]),
        "color": "#10b981",
    },
    {
        "name": "meme_viral",
        "display_name": "搞笑 / 猎奇 / 梗图整活",
        "description": "twerk、jiggle、squish、brainrot — 社媒传播感和反差感",
        "patterns": json.dumps([
            r"\b(meme|memes|funny|humor|comedy|joke|lol|lmao)\b",
            r"\b(twerk|jiggle|squish|wiggle|wobble|bounce)\b",
            r"\b(brainrot|viral|trending|into\s+the\s+mouth|drunk\s+vision)\b",
            r"\b(muscle|glow\s+up|before.?after|transformation\s+meme)\b",
            r"\b(roast|savage|cringe|cursed|unhinged|chaotic|random)\b",
            r"\b(shitpost|absurd|surreal|weird|bizarre|cursed\s+video)\b",
            r"\b(slap|punch|fight\s+(scene|meme)|reaction\s+meme|npc\s+trend)\b",
        ]),
        "template_suggestions": json.dumps([
            "Jiggle / squish physics effect",
            "Brainrot viral video maker",
            "NPC trend video template",
            "Before / after glow-up meme",
            "Muscle transformation meme",
            "Into-the-mouth comedy effect",
        ]),
        "color": "#f97316",
    },
    {
        "name": "ads_ecommerce",
        "display_name": "广告 / 电商 / 产品展示",
        "description": "UGC Video Ads、Amazon A+、Packshot 360 — Pollo/InVideo商业化",
        "patterns": json.dumps([
            r"\b(ugc\s+(video|ad|content|ads)|user.generated\s+content)\b",
            r"\b(product\s+(video|demo|showcase|ad|commercial|photography))\b",
            r"\b(amazon\s+(a\+|listing|product)|catalogue\s+photography|packshot)\b",
            r"\b(360.*(video|product|view|spin)|hero\s+shot|pack\s+shot)\b",
            r"\b(ad|ads|advertisement|advertising|commercial|promo|promotion)\b",
            r"\b(brand|branding|marketing\s+video|campaign|e.?commerce|shopify)\b",
            r"\b(unboxing|product\s+review|testimonial\s+video|sales\s+video)\b",
        ]),
        "template_suggestions": json.dumps([
            "UGC video ad template",
            "Amazon A+ product video",
            "360° product spin template",
            "Hero shot video maker",
            "Unboxing video generator",
            "Brand commercial template",
        ]),
        "color": "#8b5cf6",
    },
    {
        "name": "ugc_avatar",
        "display_name": "UGC / 虚拟人 / 口播出镜",
        "description": "Talking Avatar、LipSync、AI Presenter — InVideo/GoEnhance/Pollo",
        "patterns": json.dumps([
            r"\b(avatar|ai\s+avatar|digital\s+human|virtual\s+(human|influencer))\b",
            r"\b(talking\s+(avatar|head|photo|video)|ai\s+presenter|ai\s+anchor)\b",
            r"\b(consistent\s+character|character\s+consistency|ai\s+character)\b",
            r"\b(photo\s+to\s+video\s+avatar|image\s+to\s+avatar|face\s+to\s+video)\b",
            r"\b(ai\s+spokesperson|ai\s+actor|digital\s+presenter|virtual\s+presenter)\b",
            r"\b(voiceover|voice\s+clone|ai\s+voice|text\s+to\s+speech\s+video)\b",
            r"\b(faceless\s+video|no\s+face\s+video|ai\s+generated\s+face)\b",
        ]),
        "template_suggestions": json.dumps([
            "AI talking avatar generator",
            "Consistent character video",
            "AI presenter / spokesperson",
            "Photo to talking video",
            "Faceless AI video maker",
            "Virtual influencer template",
        ]),
        "color": "#06b6d4",
    },
    {
        "name": "social_platform",
        "display_name": "社媒平台模板",
        "description": "TikTok / Instagram / YouTube / Shorts 格式模板 — Pollo 已分渠道",
        "patterns": json.dumps([
            r"\b(tiktok|tik\s+tok|instagram\s+reel|ig\s+reel|reels?)\b",
            r"\b(youtube\s+(short|video|shorts)|youtube\s+intro|yt\s+short)\b",
            r"\b(facebook\s+(video|reel|story)|fb\s+video)\b",
            r"\b(instagram\s+(story|post|video)|ig\s+(story|post))\b",
            r"\b(social\s+media\s+(video|template|content)|platform\s+video)\b",
            r"\b(shorts?\s+(video|maker|template)|vertical\s+video|9.?16)\b",
            r"\b(channel\s+intro|outro|bumper|subscribe\s+animation)\b",
        ]),
        "template_suggestions": json.dumps([
            "TikTok video template maker",
            "Instagram Reels template",
            "YouTube Shorts maker",
            "Social media story template",
            "Channel intro / outro generator",
            "Vertical video formatter",
        ]),
        "color": "#ec4899",
    },
    {
        "name": "anime_style",
        "display_name": "动漫 / 卡通 / 风格化",
        "description": "Ghibli、Pixar、Anime、style transfer — GoEnhance/Pollo高频入口",
        "patterns": json.dumps([
            r"\b(anime|manga|ghibli|miyazaki|studio\s+ghibli)\b",
            r"\b(pixar|disney|simpsons|cartoon|comic\s+book|illustrated)\b",
            r"\b(chibi|kawaii|otaku|waifu|2d\s+animation|3d\s+(animation|cartoon))\b",
            r"\b(video.to.anime|photo.to.anime|anime\s+(filter|style|generator|converter))\b",
            r"\b(style\s+transfer|art\s+style|painterly|watercolor\s+(video|effect))\b",
            r"\b(cartoon\s+(filter|maker|effect|yourself)|animated\s+(avatar|video))\b",
        ]),
        "template_suggestions": json.dumps([
            "Ghibli style video converter",
            "Anime avatar / character generator",
            "Pixar cartoon style filter",
            "Video-to-anime converter",
            "Art style transfer template",
            "Simpsons cartoon filter",
        ]),
        "color": "#a855f7",
    },
    {
        "name": "fashion_lifestyle",
        "display_name": "时尚 / 生活方式 / 写真",
        "description": "穿搭、美妆、高端质感 — InVideo Fashion & Lifestyle / High End Luxury",
        "patterns": json.dumps([
            r"\b(fashion|style|outfit|ootd|lookbook|streetwear|luxury)\b",
            r"\b(beauty|makeup|skincare|cosmetic|glam|aesthetic)\b",
            r"\b(lifestyle|vlog|day\s+in\s+my\s+life|morning\s+routine|self.care)\b",
            r"\b(portrait\s+(video|photo)|headshot|editorial|photo\s+shoot)\b",
            r"\b(model|modeling|runway|haute\s+couture|designer)\b",
            r"\b(high.?end|premium|luxury\s+brand|lifestyle\s+brand)\b",
        ]),
        "template_suggestions": json.dumps([
            "Fashion lookbook video",
            "Luxury lifestyle brand template",
            "Beauty / makeup tutorial template",
            "OOTD outfit video maker",
            "Editorial portrait video",
            "Day-in-my-life vlog template",
        ]),
        "color": "#db2777",
    },
    {
        "name": "food_asmr",
        "display_name": "美食 / ASMR",
        "description": "Food Porn、Glass Fruits ASMR — InVideo/GoEnhance/Pollo均有",
        "patterns": json.dumps([
            r"\b(food|foods|cooking|recipe|cuisine|restaurant|chef)\b",
            r"\b(asmr|asmr\s+(video|eating|sounds?|trigger))\b",
            r"\b(food\s+(porn|video|reel|photography|review)|mukbang)\b",
            r"\b(cutting|slicing|chopping|mixing|pour|drizzle|melting)\b",
            r"\b(dessert|cake|pizza|sushi|ramen|burger|coffee\s+art)\b",
            r"\b(satisfying\s+video|oddly\s+satisfying|relaxing\s+(video|sounds?))\b",
        ]),
        "template_suggestions": json.dumps([
            "Food porn video template",
            "ASMR cutting / slicing video",
            "Glass fruits ASMR effect",
            "Satisfying cooking reel",
            "Restaurant / menu video maker",
            "Mukbang video template",
        ]),
        "color": "#ef4444",
    },
    {
        "name": "news_education",
        "display_name": "新闻 / 教育 / 知识表达",
        "description": "News Video、讲解型模板 — Pollo News/Education标签",
        "patterns": json.dumps([
            r"\b(news\s+(video|maker|generator|template|reel)|breaking\s+news)\b",
            r"\b(education|educational|tutorial|explainer|how.?to|guide)\b",
            r"\b(knowledge|learn|learning|course|lesson|classroom|teacher)\b",
            r"\b(documentary|docuseries|interview|talk\s+show|podcast\s+video)\b",
            r"\b(infographic\s+video|data\s+visualization|whiteboard\s+animation)\b",
            r"\b(science|history|technology|factual|fact\s+check|opinion\s+video)\b",
        ]),
        "template_suggestions": json.dumps([
            "AI news video generator",
            "Explainer video maker",
            "Tutorial video template",
            "Documentary-style template",
            "Infographic video maker",
            "Podcast video template",
        ]),
        "color": "#64748b",
    },
    {
        "name": "travel_outdoor",
        "display_name": "旅行 / 城市 / 户外",
        "description": "城市探店、户外 lifestyle — InVideo Iconic Locations / Great Outdoors",
        "patterns": json.dumps([
            r"\b(travel|traveling|traveller|tourism|tourist|destination)\b",
            r"\b(city|cityscape|urban|street|neighborhood|cafe\s+vlog|cafe\s+spots?)\b",
            r"\b(outdoor|outdoors|nature|landscape|scenic|wilderness|hiking)\b",
            r"\b(iconic\s+location|landmark|hidden\s+gem|bucket\s+list)\b",
            r"\b(road\s+trip|backpack|solo\s+travel|travel\s+vlog|travel\s+reel)\b",
            r"\b(beach|mountain|forest|waterfall|sunset|drone\s+shot|aerial)\b",
        ]),
        "template_suggestions": json.dumps([
            "Travel vlog video template",
            "City explore / cafe vlog reel",
            "Drone aerial footage template",
            "Iconic location showcase",
            "Road trip video maker",
            "Nature / outdoor reel template",
        ]),
        "color": "#059669",
    },
    {
        "name": "holiday_celebration",
        "display_name": "节日 / 纪念 / 情绪向内容",
        "description": "Birthday、Tribute、Halloween、季节性 — Pollo/GoEnhance节日模板",
        "patterns": json.dumps([
            r"\b(birthday\s+(video|maker|template|card|wish)|happy\s+birthday)\b",
            r"\b(tribute\s+video|memorial|in\s+memory\s+of|farewell\s+video)\b",
            r"\b(halloween|christmas|xmas|new\s+year|easter|thanksgiving)\b",
            r"\b(valentine|mother.?s\s+day|father.?s\s+day|anniversary|graduation)\b",
            r"\b(cherry\s+blossom|sakura|spring|seasonal|holiday\s+template)\b",
            r"\b(greeting\s+card|video\s+card|wish\s+video|celebration\s+video)\b",
            r"\b(fireworks|confetti|countdown|party\s+video|wedding\s+video)\b",
        ]),
        "template_suggestions": json.dumps([
            "AI birthday video maker",
            "Tribute / memorial video template",
            "Halloween effect generator",
            "Christmas greeting video",
            "Cherry blossom seasonal template",
            "New Year countdown video",
        ]),
        "color": "#14b8a6",
    },
]


PRESET_COMPETITORS = [
    {"domain": "pollo.ai",      "name": "Pollo AI",    "sitemap_url": "https://pollo.ai/sitemap.xml"},
    {"domain": "pixverse.ai",   "name": "PixVerse",    "sitemap_url": "https://pixverse.ai/sitemap.xml"},
    {"domain": "viggle.ai",     "name": "Viggle AI",   "sitemap_url": "https://viggle.ai/sitemap.xml"},
    {"domain": "haiper.ai",     "name": "Haiper AI",   "sitemap_url": "https://haiper.ai/sitemap.xml"},
    {"domain": "klingai.com",   "name": "Kling AI",    "sitemap_url": "https://klingai.com/sitemap.xml"},
    {"domain": "runwayml.com",  "name": "Runway ML",   "sitemap_url": "https://runwayml.com/sitemap.xml"},
    {"domain": "goenhan.com",   "name": "GoEnhance",   "sitemap_url": "https://goenhan.com/sitemap.xml"},
    {"domain": "invideo.io",    "name": "InVideo",     "sitemap_url": "https://invideo.io/sitemap.xml"},
]
