import json

# ─── 16 Business-aligned template categories ────────────────────────────────
# Based on actual competitor template analysis: Pollo AI, GoEnhance, InVideo

TEMPLATE_CATEGORIES = [
    {
        "name": "pet_animal",
        "display_name": "宠物 / 动物",
        "description": "宠物互动、动物运动、宠物拟人、野生动物POV",
        "patterns": json.dumps([
            r"\b(cat|cats|kitten|kitty|dog|dogs|puppy|puppies|pet|pets|animal|animals)\b",
            r"\b(bear|fox|panda|rabbit|bunny|hamster|parrot|bird|wildlife)\b",
            r"\b(pet\s+kiss(ing)?|pet\s+hug|ai\s+selfie\s+with\s+pet)\b",
            r"\b(animal\s+olympics|dog\s+diving|pet\s+diving|dog\s+challenge)\b",
            r"\b(pet.to.human|working\s+pet|pet\s+celebrity|talking\s+pet)\b",
            r"\b(bear\s+chase|animal\s+pov|animal\s+adventure|wildlife\s+pov)\b",
            r"\b(dancing\s+(cat|dog|animal|pet)|cute\s+(cat|dog|pet)\s+(video|ai))\b",
        ]),
        "template_suggestions": json.dumps([
            "Pet Kissing Video / Pet Hug Video",
            "AI Selfie with Pets",
            "Animal Olympics / Dog Diving Challenge",
            "Pet to Human / Working Pet",
            "Bear Chase / Animal POV Adventure",
            "Pet Celebrity Video",
        ]),
        "color": "#f59e0b",
    },
    {
        "name": "romance_social",
        "display_name": "情感互动 / 人物关系",
        "description": "接吻、拥抱、约会感、情侣合照 — 情侣/粉圈/社媒整活",
        "patterns": json.dumps([
            r"\b(ai\s+kiss(ing)?\s+(video|generator)|ai\s+french\s+kiss|blowing\s+kisses)\b",
            r"\b(ai\s+hug\s+(generator|video)|reunion\s+hug|hug\s+video\s+ai)\b",
            r"\b(fake\s+date\s+(video|ai)|ai\s+fake\s+date|romantic\s+night\s+out)\b",
            r"\b(polaroid\s+(duo|selfie|couple)|couple\s+memory\s+clip|duo\s+selfie)\b",
            r"\b(kiss|kissing|french\s+kiss|hug|hugging|embrace|cuddle)\b",
            r"\b(couple|romantic|romance|love|valentine|wedding|proposal)\b",
            r"\b(celebrity\s+(selfie|hug|kiss|date)|fan\s+meet)\b",
        ]),
        "template_suggestions": json.dumps([
            "AI Kissing Video / AI French Kiss Video",
            "Blowing Kisses AI",
            "AI Hug Generator / Reunion Hug Video",
            "AI Fake Date Video / Romantic Night Out",
            "Polaroid Duo Selfie / Couple Memory Clip",
        ]),
        "color": "#f43f5e",
    },
    {
        "name": "meme_viral",
        "display_name": "搞笑 / 整活 / 猎奇",
        "description": "魔性动作、夸张变形、醉酒怪诞、Meme玩法",
        "patterns": json.dumps([
            r"\b(ai\s+twerk\s+(generator|video)|twerk\s+ai|twerking\s+ai)\b",
            r"\b(ai\s+jiggle\s+(video|effect)|jiggle\s+physics\s+ai)\b",
            r"\b(into\s+the\s+mouth|squish\s+(it|video|ai)|drip\s+flip)\b",
            r"\b(drunk\s+vision\s+(video|ai)|ufo\s+(effect|video)|kaleido\s+(video|effect))\b",
            r"\b(face\s+swap\s+meme|funny\s+reaction\s+meme|meme\s+generator\s+ai)\b",
            r"\b(meme|funny|humor|comedy|viral|brainrot|npc\s+trend)\b",
            r"\b(glow\s+up|before.?after|muscle\s+meme|chaos|absurd|cursed)\b",
        ]),
        "template_suggestions": json.dumps([
            "AI Twerk Generator / AI Jiggle Video Effect",
            "Into The Mouth / Squish It / Drip Flip",
            "Drunk Vision / UFO / Kaleido",
            "Face Swap Meme Generator / Funny Reaction Meme",
        ]),
        "color": "#f97316",
    },
    {
        "name": "anime_style",
        "display_name": "动漫 / 卡通 / 风格化",
        "description": "动漫化视频/图片、角色动画、经典IP风格化",
        "patterns": json.dumps([
            r"\b(ai\s+animation\s+(generator|maker)|video\s+to\s+anime|video\s+into\s+cartoon)\b",
            r"\b(ghibli\s+(ai|generator|filter|style)|studio\s+ghibli\s+ai)\b",
            r"\b(pixar\s+(ai|generator|filter|style)|pixar.style\s+ai)\b",
            r"\b(ai\s+cartoon\s+(generator|maker|filter)|cartoon\s+yourself\s+ai)\b",
            r"\b(character\s+animation\s+ai|live\s+2d\s+animation|2d\s+animation\s+ai)\b",
            r"\b(ai\s+simpsons\s+(character|generator|filter)|snoopy\s+filter\s+ai)\b",
            r"\b(anime|manga|chibi|kawaii|animated\s+avatar|anime\s+(filter|style))\b",
        ]),
        "template_suggestions": json.dumps([
            "AI Animation Generator / Video to Anime",
            "Ghibli AI Generator / Pixar AI Generator",
            "AI Cartoon Generator / Video into Cartoon",
            "Character Animation / Live 2D Animation",
            "AI Simpsons Generator / Snoopy Filter",
        ]),
        "color": "#a855f7",
    },
    {
        "name": "ugc_avatar",
        "display_name": "人物形象 / 虚拟人 / 口播",
        "description": "虚拟人口播、一致角色、脸部替换、人像变化滤镜",
        "patterns": json.dumps([
            r"\b(photo\s+to\s+video\s+avatar|ai\s+talking\s+avatar|talking\s+avatar\s+ai)\b",
            r"\b(consistent\s+character\s+(video|ai)|character\s+consistency\s+ai)\b",
            r"\b(video\s+face\s+swap|multiple\s+face\s+swap|face\s+swap\s+video\s+ai)\b",
            r"\b(ai\s+baby\s+filter|ai\s+bald\s+filter|ai\s+beardless\s+filter|pregnant\s+ai)\b",
            r"\b(ai\s+(avatar|presenter|spokesperson|anchor)|digital\s+human|virtual\s+human)\b",
            r"\b(faceless\s+(video|channel)|ai\s+talking\s+photo|photo\s+to\s+talking)\b",
            r"\b(ai\s+age\s+(filter|progression)|face\s+aging\s+ai|old\s+face\s+ai)\b",
        ]),
        "template_suggestions": json.dumps([
            "Photo to Video Avatar / AI Talking Avatar",
            "Consistent Character Video AI",
            "Video Face Swap / Multiple Face Swap",
            "AI Baby Filter / AI Bald Filter / AI Beardless Filter",
            "Pregnant AI / AI Age Filter",
        ]),
        "color": "#06b6d4",
    },
    {
        "name": "dance_sports",
        "display_name": "运动 / 舞蹈 / 演出",
        "description": "跳舞模板、训练健身、演出表演、乐器演奏",
        "patterns": json.dumps([
            r"\b(ai\s+dance\s+(generator|video|maker)|dancing\s+girl\s+ai)\b",
            r"\b(5.minute\s+home\s+workout|home\s+workout\s+(ai|video)|workout\s+video\s+ai)\b",
            r"\b(performance\s+(clip|video|ai)|stage\s+motion\s+video|live\s+performance\s+ai)\b",
            r"\b(instrument\s+playing\s+(ai|video)|playing\s+(guitar|piano|violin)\s+ai)\b",
            r"\b(dance|dancing|dancer|choreography|tiktok\s+dance|dance\s+challenge)\b",
            r"\b(sport|sports|workout|fitness|gym|training\s+(video|montage))\b",
            r"\b(basketball|soccer|football|tennis|swimming|running|olympic)\b",
        ]),
        "template_suggestions": json.dumps([
            "AI Dance Generator / Dancing Girl",
            "5-Minute Home Workout AI",
            "Performance Clip / Stage Motion",
            "Instrument Playing AI Video",
        ]),
        "color": "#0ea5e9",
    },
    {
        "name": "music_video",
        "display_name": "音乐 / MV / 演出混剪",
        "description": "音乐视频、MV氛围片、儿歌节奏类、音乐+表演混剪",
        "patterns": json.dumps([
            r"\b(music\s+video\s+(ai|maker|generator)|ai\s+music\s+video)\b",
            r"\b(jazz\s+club\s+(invite|video)|nature\s+meditation\s+video)\b",
            r"\b(moana\s+nursery\s+rhyme|nursery\s+rhyme\s+ai|kids\s+song\s+video)\b",
            r"\b(performance\s+music\s+cut|music\s+performance\s+video)\b",
            r"\b(lip\s+sync|lipsync|karaoke\s+(video|ai)|singing\s+video\s+ai)\b",
            r"\b(music\s+visualizer|lyric\s+video|album\s+(cover|art)\s+video)\b",
            r"\b(concert|live\s+show\s+video|dj\s+(video|set)|remix\s+video)\b",
        ]),
        "template_suggestions": json.dumps([
            "Music Video AI Maker",
            "Jazz Club Invite / Nature Meditation",
            "Moana Nursery Rhyme AI",
            "Performance Music Cut",
            "AI Lip Sync / Lyric Video",
        ]),
        "color": "#10b981",
    },
    {
        "name": "cinematic_story",
        "display_name": "影视 / 叙事 / 电影感",
        "description": "电影感镜头、悬疑剧情、POV主观视角、短片生成",
        "patterns": json.dumps([
            r"\b(cinematic\s+noir|hero\s+walk\s+(video|ai)|cinematic\s+(ai|video|style))\b",
            r"\b(mystery\s+storytelling\s+ai|mystery\s+(video|scene)\s+ai)\b",
            r"\b(first.person\s+pov|pov\s+(video|ai|shot)|first\s+person\s+view\s+ai)\b",
            r"\b(movie\s+scene\s+(generator|ai)|faceless\s+story\s+video|short\s+film\s+ai)\b",
            r"\b(cinematic|noir|thriller|drama|storytelling|narrative|movie\s+trailer)\b",
            r"\b(film\s+(intro|scene|maker)|director.?s\s+cut\s+ai|advanced\s+director)\b",
            r"\b(horror\s+ai|sci.fi\s+video|fantasy\s+(video|ai)|action\s+movie\s+ai)\b",
        ]),
        "template_suggestions": json.dumps([
            "Cinematic Noir / Hero Walk",
            "Mystery Storytelling AI",
            "First-Person POV Video AI",
            "Movie Scene Generator / Faceless Story Video",
        ]),
        "color": "#6366f1",
    },
    {
        "name": "social_platform",
        "display_name": "社交媒体 / 平台模板",
        "description": "平台成片、短视频形态、频道包装、日常博主内容",
        "patterns": json.dumps([
            r"\b(instagram\s+(video|reel|story)\s+(maker|ai)|ig\s+(reel|video)\s+ai)\b",
            r"\b(tiktok\s+(video|content)\s+(maker|ai)|facebook\s+video\s+(maker|ai))\b",
            r"\b(linkedin\s+video\s+(maker|ai)|youtube\s+shorts?\s+(maker|ai|generator))\b",
            r"\b(youtube\s+(intro|outro)\s+(maker|ai)|channel\s+(intro|outro)\s+ai)\b",
            r"\b(daily\s+vlog\s+(maker|ai)|celebrity\s+video\s+ai|vlog\s+maker\s+ai)\b",
            r"\b(social\s+media\s+video\s+(ai|maker)|vertical\s+video\s+ai|reels?\s+maker)\b",
            r"\b(tiktok|instagram|youtube|facebook|linkedin|shorts|reels?)\b",
        ]),
        "template_suggestions": json.dumps([
            "Instagram Video / TikTok Video / LinkedIn Video",
            "Instagram Reels / YouTube Shorts",
            "YouTube Intro / YouTube Outro",
            "Daily Vlog AI / Celebrity Video",
        ]),
        "color": "#ec4899",
    },
    {
        "name": "ads_ecommerce",
        "display_name": "广告 / 电商 / 产品展示",
        "description": "UGC广告、品牌宣传、商品展示、电商素材",
        "patterns": json.dumps([
            r"\b(ugc\s+video\s+(ads?|maker|ai)|beard\s+oil\s+ugc|ugc\s+ad\s+(generator|ai))\b",
            r"\b(brand\s+promo\s+(video|ai)|mercedes\s+promo|culinary\s+art\s+promo)\b",
            r"\b(360.*(product|video|spin)|hero\s+shot\s+(video|ai)|packshot\s+360)\b",
            r"\b(amazon\s+(a\+|primary\s+image|listing)|catalogue\s+photography\s+ai)\b",
            r"\b(product\s+(video|demo|showcase|ad)|commercial\s+(video|ai)|ad\s+maker)\b",
            r"\b(ugc|unboxing|testimonial\s+video|sales\s+video|shopify\s+video)\b",
            r"\b(e.?commerce\s+video|product\s+photography\s+ai|brand\s+video\s+ai)\b",
        ]),
        "template_suggestions": json.dumps([
            "UGC Video Ads / Beard Oil UGC Ad",
            "Mercedes G-Class Promo / Brand Promo",
            "360° Product Video / Hero Shot / Packshot 360",
            "Amazon A+ Content / Amazon Primary Image",
            "Catalogue Photography AI",
        ]),
        "color": "#8b5cf6",
    },
    {
        "name": "fashion_lifestyle",
        "display_name": "时尚 / 生活方式",
        "description": "穿搭美妆、日常生活感、城市探店、高级质感素材",
        "patterns": json.dumps([
            r"\b(fashion\s+(lifestyle|video|ai)|high\s+end\s+luxury\s+(video|ai))\b",
            r"\b(daily\s+vlog\s+(maker|ai)|day\s+in\s+my\s+life\s+ai|lookbook\s+(video|ai))\b",
            r"\b(best\s+work\s+from\s+cafe|cafe\s+(vlog|spots?|video)\s+ai)\b",
            r"\b(indoor\s+studio\s+(video|ai)|retro\s+modern\s+video)\b",
            r"\b(fashion|style|outfit|ootd|beauty|makeup|skincare|luxury|lifestyle)\b",
            r"\b(vlog|aesthetic|editorial|portrait\s+video|model\s+video)\b",
        ]),
        "template_suggestions": json.dumps([
            "Fashion & Lifestyle / High End Luxury",
            "Daily Vlog / Looks",
            "Best Work From Cafe Spots",
            "Indoor Studio / Retro Modern",
        ]),
        "color": "#db2777",
    },
    {
        "name": "food_asmr",
        "display_name": "美食 / ASMR",
        "description": "食物质感、切割声音疗愈、沉浸式声音视频、烹饪餐饮宣传",
        "patterns": json.dumps([
            r"\b(food\s+porn\s+(video|ai)|food\s+(video|reel|photography)\s+ai)\b",
            r"\b(glass\s+fruits?\s+(cutting|asmr|ai)|fruits?\s+cutting\s+asmr)\b",
            r"\b(ai\s+asmr\s+(video|generator)|asmr\s+(video|content)\s+ai)\b",
            r"\b(culinary\s+art\s+promo|restaurant\s+(video|promo)\s+ai)\b",
            r"\b(asmr|food|cooking|recipe|mukbang|satisfying|oddly\s+satisfying)\b",
            r"\b(cutting|slicing|chopping|drizzle|melting|food\s+close.?up)\b",
        ]),
        "template_suggestions": json.dumps([
            "Food Porn Video AI",
            "Glass Fruits Cutting ASMR",
            "AI ASMR Video Generator",
            "Culinary Art Promo / Restaurant Video",
        ]),
        "color": "#ef4444",
    },
    {
        "name": "travel_outdoor",
        "display_name": "旅行 / 户外 / 城市",
        "description": "城市地标、户外自然、B-Roll素材、风景照片动效",
        "patterns": json.dumps([
            r"\b(iconic\s+locations?\s+(video|ai)|landmark\s+(video|ai))\b",
            r"\b(the\s+great\s+outdoors\s+(video|ai)|outdoor\s+(video|reel)\s+ai)\b",
            r"\b(b.roll\s+(video|ai|footage|maker)|broll\s+ai)\b",
            r"\b(travel\s+photo\s+(motion|animation)|nature\s+photo\s+animation)\b",
            r"\b(travel|traveling|tourism|destination|road\s+trip|city\s+vlog)\b",
            r"\b(drone\s+(shot|footage|video)\s+ai|aerial\s+video|landscape\s+video)\b",
            r"\b(beach|mountain|forest|waterfall|sunset|nature|outdoor|hiking)\b",
        ]),
        "template_suggestions": json.dumps([
            "Iconic Locations Video AI",
            "The Great Outdoors Video",
            "B-Roll Video AI",
            "Travel Photo Motion / Nature Photo Animation",
        ]),
        "color": "#059669",
    },
    {
        "name": "news_education",
        "display_name": "资讯 / 教育 / 知识",
        "description": "新闻成片、知识讲解、评测内容、无人出镜视频",
        "patterns": json.dumps([
            r"\b(news\s+video\s+(ai|maker|generator)|ai\s+news\s+video)\b",
            r"\b(education\s+explainer\s+(video|ai)|explainer\s+video\s+(ai|maker))\b",
            r"\b(the\s+reviewer\s+(video|ai)|product\s+review\s+video\s+ai)\b",
            r"\b(faceless\s+(video|channel|content)\s*(maker|ai)?|no\s+face\s+video\s+ai)\b",
            r"\b(tutorial|how.?to|educational|documentary|infographic\s+video)\b",
            r"\b(knowledge|learn|course|lesson|whiteboard\s+animation|podcast\s+video)\b",
        ]),
        "template_suggestions": json.dumps([
            "News Video AI Maker",
            "Education Explainer Video",
            "The Reviewer Video AI",
            "Faceless Video / Faceless Channel",
        ]),
        "color": "#64748b",
    },
    {
        "name": "holiday_celebration",
        "display_name": "节日 / 纪念 / 情绪",
        "description": "生日祝福、致敬纪念、老照片修复动效、节庆氛围短片",
        "patterns": json.dumps([
            r"\b(birthday\s+video\s+(ai|maker)|happy\s+birthday\s+(video|ai))\b",
            r"\b(tribute\s+video\s+(ai|maker)|memorial\s+video\s+ai)\b",
            r"\b(old\s+photo\s+(animation|ai|restore)|photo\s+restoration\s+ai)\b",
            r"\b(holiday\s+memory\s+reel|halloween\s+(effect|video)\s+ai)\b",
            r"\b(christmas|xmas|halloween|new\s+year|easter|thanksgiving)\b",
            r"\b(valentine|mother.?s\s+day|father.?s\s+day|anniversary|graduation)\b",
            r"\b(cherry\s+blossom|sakura|fireworks\s+video|celebration\s+video)\b",
        ]),
        "template_suggestions": json.dumps([
            "Birthday Video AI Maker",
            "Tribute Video / Memorial Video",
            "Old Photo Animation AI",
            "Holiday Memory Reel / Halloween Effect",
        ]),
        "color": "#14b8a6",
    },
    {
        "name": "creative_effects",
        "display_name": "创意特效 / 后期工具",
        "description": "基础视觉特效、镜头语言、后期工具、道具场景替换",
        "patterns": json.dumps([
            r"\b(video\s+effect\s+(ai|generator)|ai\s+video\s+(filter|effect)|vhs\s+(effect|ai))\b",
            r"\b(whip\s+pan\s+(video|ai)|camera\s+angles\s+ai|extract\s+shot\s+ai)\b",
            r"\b(ai\s+relight\s+(video|tool)|ai\s+colorist|video\s+relight\s+ai)\b",
            r"\b(inpaint\s+(and\s+cleanup|video|ai)|video\s+cleanup\s+ai|remove\s+object\s+ai)\b",
            r"\b(re.frame\s+(video|ai)|video\s+reframe\s+ai|aspect\s+ratio\s+ai)\b",
            r"\b(prop\s+swap\s+(video|ai)|virtual\s+production\s+ai|overlay\s+(video|effect)\s+ai)\b",
            r"\b(video\s+(effect|filter|transition)|slow\s+motion\s+ai|speed\s+ramp\s+ai)\b",
        ]),
        "template_suggestions": json.dumps([
            "Video Effect AI / AI Video Filter / VHS Effect",
            "Whip Pan / Angles / Extract Shot",
            "Relight / AI Colorist / Inpaint and Cleanup",
            "Re-frame / Prop Swap / Virtual Production / Overlay",
        ]),
        "color": "#7c3aed",
    },
]


PRESET_COMPETITORS = [
    {"domain": "pollo.ai",      "name": "Pollo AI",    "sitemap_url": "https://pollo.ai/sitemap.xml"},
    {"domain": "pixverse.ai",   "name": "PixVerse",    "sitemap_url": "https://pixverse.ai/sitemap.xml"},
    {"domain": "viggle.ai",     "name": "Viggle AI",   "sitemap_url": "https://viggle.ai/sitemap.xml"},
    {"domain": "haiper.ai",     "name": "Haiper AI",   "sitemap_url": "https://haiper.ai/sitemap.xml"},
    {"domain": "klingai.com",   "name": "Kling AI",    "sitemap_url": "https://klingai.com/sitemap.xml"},
    {"domain": "runwayml.com",  "name": "Runway ML",   "sitemap_url": "https://runwayml.com/sitemap.xml"},
    {"domain": "goenhan.com",   "name": "GoEnhance",   "sitemap_url": "https://goenhan.com/sitemap.xml"},
    {"domain": "invideo.io",    "name": "InVideo",     "sitemap_url": "https://invideo.io/sitemap.xml"},
]
